import { AppSettings } from "./types";

export const APP_NAME = "超强DKD";

export const DEFAULT_SETTINGS: AppSettings = {
  appName: APP_NAME,
  accounts: [
    {
      id: "main",
      name: "x4920v",
      enabled: true,
      isMasterAccount: true,
      binance: {
        apiKey: "oDQleHC2fKUyLORiNvYxDhbjMwd0tSJerZ16UpDeodVpftUt5rajHDac8f0qhPZX",
        secretKey: "APwIfMbrtqw3oo0Xi3xmm4JgyXepOI1m0GVAurggIyw0VWJ1hWU0QpXJ3e7Yxoes",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:06:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: true,
          interval: "15m",
          startTime: "00:07:36.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:13:54.300",
          minVolumeM1: 500000,
          priceChangeK1: [0, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.300",
          cooldown: 0,
          preferredMode: 'volume',
          conditions: {
            k2: { enabled: true, range: [4, 8.9] },
            a: { 
              enabled: true, 
              mode: 'fixed', 
              fixedRange: [0, 3],
              relativeRange: [0, 50]
            },
            m: { enabled: true, range: [6980000, 1000000000] },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 50,
        maxPosition: 40000,
        tpMode: 'ratio',
        tpRatio: 42,
        tpRatio1: 30,
        tpRatio2: 42,
        tpQtyRatio1: 50,
        tpQtyRatio2: 50,
        tpFixed: 2,
        tpEnabled: true,
        slMode: 'ratio',
        slRatio: 85,
        slFixed: 3,
        slEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 14.9,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 518,
        retentionThreshold: 488,
        alarmThreshold: 5,
      },
    },
    {
      id: "1",
      name: "x2000",
      enabled: false,
      isMasterAccount: false,
      binance: {
        apiKey: "lrzuX7LBhPcaDzHLFsPVzy8bybe9GXFb3jbqIIs8VpmKEj8FenulCnfs1pHrO3Gr",
        secretKey: "CB6pScEbBd90tubbL9Wy9boJJV4cDXzOoeDVGeUcZFM2oo7ciJNjnsO1tLbs1w3S",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:21:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:10:16.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:14:51.600",
          minVolumeM1: 500000,
          priceChangeK1: [0, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.600",
          cooldown: 0,
          preferredMode: 'k2',
          conditions: {
            k2: { enabled: true, range: [4, 8.9] },
            a: { 
              enabled: true, 
              mode: 'fixed', 
              fixedRange: [0, 3],
              relativeRange: [0, 50]
            },
            m: { enabled: true, range: [19800000, 1000000000] },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 50,
        maxPosition: 40000,
        tpMode: 'ratio',
        tpRatio: 44,
        tpRatio1: 30,
        tpRatio2: 42,
        tpQtyRatio1: 50,
        tpQtyRatio2: 50,
        tpFixed: 2,
        tpEnabled: true,
        slMode: 'ratio',
        slRatio: 85,
        slFixed: 3,
        slEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 89,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 2088,
        retentionThreshold: 1988,
        alarmThreshold: 5,
      },
    },
    {
      id: "2",
      name: "x4920z",
      enabled: false,
      isMasterAccount: false,
      binance: {
        apiKey: "3lK2MIDW6P2boCaPqJifTIYYCUAOjDH82M0ti8K9mtj4E0fvup47qVVl4YVdXVa7",
        secretKey: "2Rqb5Le4CdYfmHvgckcR5CXHhuvtRPRgTXHy6nWNjmVPExSdaYyZL5FuotmxjDKK",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:36:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:10:26.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:14:51.300",
          minVolumeM1: 500000,
          priceChangeK1: [0, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.650",
          cooldown: 0,
          preferredMode: 'amp',
          conditions: {
            k2: { enabled: true, range: [4, 8.9] },
            a: { 
              enabled: true, 
              mode: 'fixed', 
              fixedRange: [0, 3],
              relativeRange: [0, 50]
            },
            m: { enabled: true, range: [6980000, 1000000000] },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 50,
        maxPosition: 40000,
        tpMode: 'ratio',
        tpRatio: 42,
        tpRatio1: 30,
        tpRatio2: 42,
        tpQtyRatio1: 50,
        tpQtyRatio2: 50,
        tpFixed: 2,
        tpEnabled: true,
        slMode: 'ratio',
        slRatio: 85,
        slFixed: 3,
        slEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 14.9,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 518,
        retentionThreshold: 488,
        alarmThreshold: 5,
      },
    },
    {
      id: "3",
      name: "x4920k",
      enabled: false,
      isMasterAccount: false,
      binance: {
        apiKey: "KNbFTnrqqZmd4z6tiGwB9r9IM4SlnAvE1Nj18gFLIXZaH8vRmECYDfuaCzxPag9j",
        secretKey: "NbmnJCRTT1ZGwYd3JuKcHo5t3bunhbscLRHCXovjJIivfyqllX48hOVAmvvicGMh",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:51:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:10:36.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:14:51.400",
          minVolumeM1: 500000,
          priceChangeK1: [0, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.700",
          cooldown: 0,
          preferredMode: 'k2',
          conditions: {
            k2: { enabled: true, range: [4, 8.9] },
            a: { 
              enabled: true, 
              mode: 'fixed', 
              fixedRange: [0, 3],
              relativeRange: [0, 50]
            },
            m: { enabled: true, range: [6980000, 1000000000] },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 50,
        maxPosition: 40000,
        tpMode: 'ratio',
        tpRatio: 42,
        tpRatio1: 30,
        tpRatio2: 42,
        tpQtyRatio1: 50,
        tpQtyRatio2: 50,
        tpFixed: 2,
        tpEnabled: true,
        slMode: 'ratio',
        slRatio: 85,
        slFixed: 3,
        slEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        positiveWindow: 0.7,
        maxHoldTime: 14.9,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 518,
        retentionThreshold: 488,
        alarmThreshold: 5,
      },
    },
    {
      id: "4",
      name: "x49km",
      enabled: false,
      isMasterAccount: false,
      binance: {
        apiKey: "K9YcyBVVddSjatOOIZ0b1bewVGHcEbDUAqpdwpNICPZ0FMdzy1CC6yT68dafkguS",
        secretKey: "8ed9UhEweSXZZVGY8nP9Url7ElHxQkl4Hp1DJAhj5DaMlIWwO9QwjuQOXxT39i8h",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:06:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:10:46.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:14:52.300",
          minVolumeM1: 500000,
          priceChangeK1: [0, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          interval: "15m",
          startTime: "00:14:59.750",
          cooldown: 0,
          preferredMode: 'k2',
          conditions: {
            k2: { enabled: true, range: [4, 8.9] },
            a: { 
              enabled: true, 
              mode: 'fixed', 
              fixedRange: [0, 3],
              relativeRange: [0, 50]
            },
            m: { enabled: true, range: [6980000, 1000000000] },
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 50,
        maxPosition: 40000,
        tpMode: 'ratio',
        tpRatio: 42,
        tpRatio1: 30,
        tpRatio2: 42,
        tpQtyRatio1: 50,
        tpQtyRatio2: 50,
        tpFixed: 2,
        tpEnabled: true,
        slMode: 'ratio',
        slRatio: 85,
        slFixed: 3,
        slEnabled: true,
        mLinkEnabled: true,
        mLinkValue: 6000,
        positiveWindow: 0.7,
        maxHoldTime: 14.9,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
      },
      withdrawal: {
        withdrawalThreshold: 2088,
        retentionThreshold: 1988,
        alarmThreshold: 5,
      },
    }
  ],
  email: {
    enabled: true,
    sender: "",
    receiver: "",
    smtpServer: "",
    smtpPort: 465,
    password: "",
    minBalance: 5,
    maxConsecutiveLoss: 30000,
  },
  auth: {
    username: "admin",
    password: "Xxxxxx123!",
  },
};
